# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: get covid county data

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: '30 */3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install   
    - run: node getUS.js   
    - name: Commit files
      run: |
        git config --local user.email "covidUSstate-action@amazingshellyyy.com"
        git config --local user.name "amazingshellyyy.covidCAcounty"
        git commit -m "Add changes for US state" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.COVID_DATA_TOKEN }}
